// <auto-generated />
using System;
using Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(RestauranteContext))]
    partial class RestauranteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda");
                });

            modelBuilder.Entity("Domain.ComandaMercaderia", b =>
                {
                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("ComandaMercaderiaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("MercaderiaId");

                    b.ToTable("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega");

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salón"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Pedidos Ya"
                        });
                });

            modelBuilder.Entity("Domain.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercaderiaId"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia");

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "https://www.recetin.com/wp-content/uploads/2013/10/palitos_mozzarella.jpg",
                            Ingredientes = "Pan rallado, huevo, muzarella",
                            Nombre = "Bastones de Muzzarella",
                            Precio = 800,
                            Preparacion = "Cortar la muzzarella en bastones, pasar por huevo y pan rallado. Freir en aceite caliente hasta dorar. Servir caliente",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "https://statics.diariomendoza.com.ar/2021/05/61a5306da6e50.jpg",
                            Ingredientes = "Masa, carne picada, cebolla, huevo",
                            Nombre = "Empanadas fritas",
                            Precio = 250,
                            Preparacion = "Preparar la masa con harina, sal, agua y grasa. Rellenar con carne, cebolla, huevo. Freir en aceite caliente hasta dorar",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "https://vinomanos.com/wp-content/uploads/2019/02/milanesas-receta.jpg",
                            Ingredientes = "carne, sal, ajo, perejil, pan rallado, huevo",
                            Nombre = "Milanesa",
                            Precio = 1500,
                            Preparacion = "Condimentar filetes de carne con sal, ajo y perejil. Pasar por huevo batido y pan rallado. Freir en aceite caliente hasta dorar.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "https://previews.123rf.com/images/nblxer/nblxer1502/nblxer150200201/37174399-hamburguesa-casera-cerca-con-lechuga-fresca-verde-tomate-y-cebolla-roja-sobre-fondo-r%C3%BAstico.jpg",
                            Ingredientes = "carne picada, pan, tomate, lechuga, cebolla, aderezo",
                            Nombre = "Hamburguesa",
                            Precio = 1200,
                            Preparacion = "Formar carne picada en disco. Cocinar a la parrilla o sartén. Armar hamburguesa en pan con lechuga, tomate, cebolla y aderezo a gusto.",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "https://chefs4estaciones.com/wp-content/uploads/2020/09/ravioles-con-salsa-de-3-quesos.jpg",
                            Ingredientes = "Masa para ravioles, ricotta, espinacas, huevo, sal y pimienta, leche, harina, manteca",
                            Nombre = "Ravioles con salsa blanca",
                            Precio = 1800,
                            Preparacion = "Cocinar ravioles rellenos de ricotta y espinacas en agua con sal. Para la salsa blanca: derretir manteca, agregar harina, leche y condimentos.",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "https://imag.bonviveur.com/tallarines-a-la-bolonesa.jpg",
                            Ingredientes = "Pasta para tallarines, agua, carne picada, cebolla, ajo, tomate, aceite, sal y pimienta",
                            Nombre = "Tallarines con bolognesa",
                            Precio = 1700,
                            Preparacion = "Cocinar tallarines. En sartén, dorar carne picada en aceite. Agregar cebolla, ajo, tomate, sal y pimienta. Servir sobre los tallarines",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "https://billiken.lat/wp-content/uploads/2022/06/asado-carne-cocinada-a-la-parrilla-quimica-SITIO.jpg",
                            Ingredientes = "vacío, asado, entraña, sal gruesa, carbón, chimichurri o salsa criolla.",
                            Nombre = "Asado",
                            Precio = 2500,
                            Preparacion = "Encender fuego con carbón en la parrilla. Salar la carne. Cocinar a fuego medio/alto hasta lograr el término deseado. Cortar en tiras.",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 8,
                            Imagen = "https://lasrecetasdelchef.net/wp-content/uploads/2016/11/matambre-a-la-pizza.jpg",
                            Ingredientes = "matambre, queso mozzarella, salsa de tomate, orégano, jamón cocido",
                            Nombre = "Matambre a la pizza",
                            Precio = 2300,
                            Preparacion = "Limpiar matambre, estirar con mazo y salpimentar. Cocinarlo en la parilla. Colocar por encima jamón, queso, salsa de tomate y oregano. Cortar y servir",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "https://www.clarin.com/img/2022/10/05/utIOlIIyB_720x0__1.jpg",
                            Ingredientes = "Masa para pizza, salsa de tomate, muzarella, aceitunas",
                            Nombre = "Pizza de Muzarella",
                            Precio = 1900,
                            Preparacion = "Estirar masa para pizza. Cubrir con salsa de tomate, queso muzarella y orégano. Cocinar en horno precalentado a 200°C por 10-15 min.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "https://as2.ftcdn.net/v2/jpg/02/96/96/71/1000_F_296967135_DAjY06XgRvqzYr3WYzHvmQp4C66QxM00.jpg",
                            Ingredientes = "Masa para pizza, salsa de tomate, muzarella, calabresa",
                            Nombre = "Pizza de Calabresa",
                            Precio = 2000,
                            Preparacion = "Estirar masa para pizza. Cubrir con salsa de tomate, queso muzarella, rodajas de calabresa. Cocinar en horno precalentado a 200°C por 10-15 min",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "https://super22deoctubre.com.ar/wp-content/uploads/2020/12/IMG_1046.jpg",
                            Ingredientes = "Pan de miga, jamon, queso, huevo duro, mayonesa",
                            Nombre = "Sanguche de miga",
                            Precio = 500,
                            Preparacion = "Untar mayonesa en pan de miga. Rellenar con jamón, queso y huevo duro. ",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "https://www.deliciosi.com/images/2200/2227/sandwich-de-pollo-desmenuzado.jpg",
                            Ingredientes = "Pan, pollo cocido y desmenuzado, lechuga, tomate, cebolla, mayonesa, sal y pimienta.",
                            Nombre = "Sanguche de pollo",
                            Precio = 850,
                            Preparacion = "Mezclar pollo, mayonesa, sal y pimienta. Untar pan con la mezcla. Agregar lechuga, tomate y cebolla. Servir frío o tostado.",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 13,
                            Imagen = "https://www.cocinacaserayfacil.net/wp-content/uploads/2018/06/Ensalada-cesar.jpg",
                            Ingredientes = "Lechuga, pollo,crotones, parmesano, ajo, mayonesa, jugo de limón, aceite, salsa inglesa, mostaza de Dijon",
                            Nombre = "Ensalada Caesar",
                            Precio = 750,
                            Preparacion = "Cortar lechuga y colocar en ensaladera. Agregar pollo, crotones y parmesano. Mezclar ajo, mayonesa, limón, aceite, salsa inglesa y mostaza para preparar la salsa. Agregar a la ensalada",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "https://cuk-it.com/wp-content/uploads/2020/11/thumb06-1-e1635893831894.jpg",
                            Ingredientes = "Papas, zanahorias, arvejas, mayonesa",
                            Nombre = "Ensalada Rusa",
                            Precio = 750,
                            Preparacion = "Cocinar papas, zanahorias y huevo. Cortar en cubos y mezclar con mayonesa y sal. Enfriar antes de servir.",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "https://previews.123rf.com/images/aryutkin/aryutkin2204/aryutkin220400017/185343105-la-gran-cantidad-de-botellas-de-vidrio-de-coca-cola-en-el-mostrador-del-supermercado-regi%C3%B3n-de.jpg",
                            Ingredientes = " Botella de Coca-Cola x500ml",
                            Nombre = "Coca-Cola",
                            Precio = 350,
                            Preparacion = "-",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "https://www.golomax.com.ar/uploads/centum/articles/original/13492_1.jpg",
                            Ingredientes = "Botella de Agua x500ml",
                            Nombre = "Agua Villavicencio",
                            Precio = 250,
                            Preparacion = "-",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "https://thumbs.dreamstime.com/b/pinta-de-honey-brown-beer-51858208.jpg",
                            Ingredientes = "Chopp de cerveza Honey",
                            Nombre = "Cerveza Honey",
                            Precio = 600,
                            Preparacion = "-",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "https://www.clarin.com/img/2020/08/18/PY22-FZSu_1256x620__2.jpg#1628113269253",
                            Ingredientes = "Chopp de cerveza IPA",
                            Nombre = "Cerveza IPA",
                            Precio = 600,
                            Preparacion = "-",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "https://www.lactaid.com/sites/lactaid_us/files/recipe-images/easy_flan2.jpg",
                            Ingredientes = "Leche, huevos, azúcar y caramelo.",
                            Nombre = "Flan",
                            Precio = 700,
                            Preparacion = "Mezclar 1L de leche, 6 huevos, 150g de azúcar. Verter en molde acaramelado y hornear a baño de María a 180°C por 1 hora. Enfriar y servir.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 20,
                            Imagen = "https://www.bancodealimentoschicago.org/wp-content/uploads/2022/04/Fruit-Salad.jpg",
                            Ingredientes = "Naranja, manzana, uva, kiwi, durazno, anana, jugo de naranja",
                            Nombre = "Copa Ensalada de frutas",
                            Precio = 700,
                            Preparacion = "Picar las frutas en cubos. Mezclar con jugo de naranja. Refrigerador por 30 minutos. Servir frío.",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia");

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Entrada"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minutas"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensaladas"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cerveza Artesanal"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Domain.Comanda", b =>
                {
                    b.HasOne("Domain.FormaEntrega", "FormaEntrega")
                        .WithMany("Comanda")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Domain.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Comanda", "Comanda")
                        .WithMany("ComandaMercaderia")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Mercaderia", "Mercaderia")
                        .WithMany("ComandaMercaderia")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Domain.Mercaderia", b =>
                {
                    b.HasOne("Domain.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderia")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Domain.Comanda", b =>
                {
                    b.Navigation("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.FormaEntrega", b =>
                {
                    b.Navigation("Comanda");
                });

            modelBuilder.Entity("Domain.Mercaderia", b =>
                {
                    b.Navigation("ComandaMercaderia");
                });

            modelBuilder.Entity("Domain.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderia");
                });
#pragma warning restore 612, 618
        }
    }
}
